name: Deploy Frontend
on:
  push:
    branches:
      - main
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t sakovskidev/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true sakovskidev/react-test npm test
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: react-docker
          environment_name: Reactdocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-184235572649
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip